[package]
name = "dyntype"
version = "0.0.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
vecmat = { path = "../vecmat", features = ["nightly"] }
