language: rust

os: linux
dist: bionic

rust: stable

addons:
  apt:
    packages:
      - clang
      - cmake
      - make
      - python3

before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y ocl-icd-opencl-dev pocl-opencl-icd libpocl-dev


script:
  - python3 -m manage test --cxx-compiler clang++ --cxx-no-pch
