language: cpp

compiler:
  - gcc
  - clang

os: linux
dist: bionic

before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y ocl-icd-opencl-dev pocl-opencl-icd libpocl-dev

addons:
  apt:
    packages:
      - cmake
      #- lcov
      #- curl

script:
  - mkdir build
  - cd build
  - cmake ..
  - make test_unit test_dev
  - cd ..
  - ./build/src/test/test_unit
  - ./build/src/test/test_dev

#after_success:
#  - ./script/cov.sh
#  - bash <(curl -s https://codecov.io/bash) -f .coverage.info || echo "Codecov did not collect coverage reports"
