language: rust

os: linux
dist: bionic

rust: stable

addons:
  apt:
    packages:
      - clang
      - cmake
      - make

before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y libgtest-dev libsdl2-dev ocl-icd-opencl-dev pocl-opencl-icd libpocl-dev

script:
  - cargo test
