[workspace]

members = [
    "vecmat",
    "ccgeom",
    "includer",
    "kernel",
    "base",
    "types",
    "old_types",
    "type-macros",
    "objects",
    "processing",
    "viewer",
    "samples",
]
