[build]
target = "renderer-wgpu/web/index.html"
dist = "dist"
example = "viewer"
features = ["web"]

[watch]
watch = ["renderer-wgpu", "scene", "objects", "examples"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
