if(NOT CMAKE_CL_COMPILE_OBJECT)
    set(CMAKE_CL_COMPILER_TARGET "spir-unknown-unknown")
endif()
set(CMAKE_INCLUDE_FLAG_CL "-I")
if(NOT CMAKE_CL_COMPILE_OBJECT)
    set(CMAKE_CL_COMPILE_OBJECT "\
<CMAKE_CL_COMPILER> \
-x cl --std=cl1.2 \
-S -emit-llvm --target=<CMAKE_CL_COMPILER_TARGET> \
-Xclang -finclude-default-header \
<DEFINES> <INCLUDES> <FLAGS> \
<SOURCE> -o <OBJECT>\
    ")
endif()
set(CMAKE_CL_INFORMATION_LOADED 1)

set(CMAKE_CL_CREATE_STATIC_LIBRARY
    "llvm-link -S <LINK_FLAGS> <OBJECTS> -o <TARGET>"
    "llvm-opencl <TARGET>"
)

set(CMAKE_CL_CREATE_SHARED_LIBRARY "")
set(CMAKE_CL_CREATE_SHARED_MODULE "")
set(CMAKE_CL_LINK_EXECUTABLE "")
