[package]
name = "hypertrace-processing"
version = "0.0.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[dependencies]
ocl = "0.19"
base = { package = "hypertrace-base", path = "../base" }
types = { package = "hypertrace-types", path = "../types" }
ocl-include = { path = "../includer" }
