[package]
name = "hypertrace-types"
version = "0.0.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
vecmat = { path = "../vecmat" }
num-integer = "0.1"
ref-cast = "1.0"
fxhash = "0.2"
