SET(CMAKE_SYSTEM_NAME Generic)


set(CMAKE_C_COMPILER clang-15)
set(CMAKE_CXX_COMPILER clang++-15)

set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)

set(CMAKE_C_FLAGS "-c -target spir -O0 -emit-llvm")
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} -cl-std=clc++2021")

set(CMAKE_C_OUTPUT_EXTENSION ".bc")
set(CMAKE_CXX_OUTPUT_EXTENSION ${CMAKE_C_OUTPUT_EXTENSION})


set(CMAKE_C_LINK_EXECUTABLE "llvm-spirv-15 <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET>")
set(CMAKE_CXX_LINK_EXECUTABLE ${CMAKE_C_LINK_EXECUTABLE})

set(CMAKE_EXECUTABLE_SUFFIX_C ".spv")
set(CMAKE_EXECUTABLE_SUFFIX_CXX ".spv")
