[package]
name = "hypertrace-samples"
version = "0.0.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
sdl2 = "0.34"
ocl = "0.19"
base = { package = "hypertrace-base", path = "../base" }
view = { package = "hypertrace-viewer", path = "../viewer" }
proc = { package = "hypertrace-processing", path = "../proc" }
clap = "2.33"
