[package]
name = "hypertrace-samples"
version = "0.0.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
base = { package = "hypertrace-base", path = "../base" }
viewer = { package = "hypertrace-viewer", path = "../viewer" }
sdl2 = "0.34"
