[package]
name = "hypertrace-samples"
version = "0.0.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
sdl2 = "0.34"
ocl = "0.19"
ocl-include = { path = "../includer" }
hy-base = { path = "../base" }
hy-types = { path = "../types" }
hy-viewer = { path = "../viewer" }
hy-objects = { path = "../objects" }
hy-processing = { path = "../processing" }
clap = "2.33"
vecmat = { path = "../vecmat" }
