[package]
name = "hypertrace-examples"
version = "0.0.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0"
objects = { package = "hypertrace-objects", path = "../objects" }
ccgeom = "0.1"
vecmat = "0.7"
hypertrace-renderer = { path = "../renderer" }
winit = { version = "0.30.13", default-features = false, features = ["rwh_06"] }
wgpu = { version = "30.0.1", default-features = false, features = ["std"] }
wgame = { path = "../../wgame/wgame", default-features = false, features = ["desktop"] }

[[bin]]
name = "hyperbolic"
path = "src/bin/hyperbolic/main.rs"

[[bin]]
name = "euclidean"
path = "src/bin/euclidean/main.rs"

[[bin]]
name = "spherical"
path = "src/bin/spherical/main.rs"

[[bin]]
name = "fog"
path = "src/bin/fog/main.rs"

[[bin]]
name = "ball-tilings"
path = "src/bin/ball-tilings/main.rs"
