[package]
name = "hypertrace-examples"
version = "0.0.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0"
objects = { package = "hypertrace-objects", path = "../objects" }
ccgeom = "0.1"
vecmat = "0.7"
hypertrace-renderer = { path = "../renderer" }
wgpu = { version = "30.0.1", default-features = false, features = ["std"] }
wgame = { path = "../../wgame/wgame", default-features = false, features = ["desktop"] }

[[bin]]
name = "hy"
path = "src/bin/hy/main.rs"

[[bin]]
name = "eu"
path = "src/bin/eu/main.rs"

[[bin]]
name = "sp"
path = "src/bin/sp/main.rs"

[[bin]]
name = "sp-fog"
path = "src/bin/sp-fog/main.rs"
