[package]
name = "hypertrace-renderer"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1"
scene_ir = { package = "hypertrace-scene", path = "../scene" }
bytemuck = { version = "1", features = ["derive"] }
futures = { version = "0.3", features = ["executor"] }
wgpu = { version = "30.0.1", default-features = false, features = ["std", "wgsl"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = { version = "30.0.1", default-features = false, features = ["vulkan", "metal", "dx12", "gles"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
wgpu = { version = "30.0.1", default-features = false, features = ["webgpu"] }

[dev-dependencies]
ccgeom = "0.1"
objects = { package = "hypertrace-objects", path = "../objects" }
