[package]
name = "hypertrace-base"
version = "0.0.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[dependencies]
ocl = "0.19"
types = { package = "hypertrace-types", path = "../types" }
